// <auto-generated />
using System;
using Library_managment_system_API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_managment_system_API.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20240731080833_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library_managment_system_API.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("Ordered")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookCategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Thomas H. Cormen",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 50000.0,
                            Title = "Author Thomas Cormen’s “Algorithms Unlocked” seeks to take away the mystery of technology and unveils the secrets behind its inner workings"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Steven S. Skiena",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 30000.0,
                            Title = "The Algorithm Design Manual” is an introduction to creating algorithms on your own from scratch"
                        },
                        new
                        {
                            Id = 3,
                            Author = " Robert Sedgewick and Kevin Wayne ",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 40000.0,
                            Title = "A simple title for a not so simple book, “Algorithms” is incredibly succinct in its naming and belies the full depth of what it covers"
                        },
                        new
                        {
                            Id = 4,
                            Author = "E. Oberg",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 30000.0,
                            Title = "Is it possible to find a book with all the information you need on machinery, metalworking, manufacturing, and even architecture"
                        },
                        new
                        {
                            Id = 5,
                            Author = "An Introduction to Mechanical Engineering by J. Wickert and  K. Lewis",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 4000.0,
                            Title = "A simple title for a not so simple book, “Algorithms” is incredibly succinct in its naming and belies the full depth of what it covers"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Mechanics of Fluids",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 3000.0,
                            Title = "This work should lie on the bedside table of every mechanical engineer who is constantly improving their knowledge"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Calculus: Early Transcendentals by James Stewart",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 10000.0,
                            Title = "It’s written in a very easy and intuitive style and has a ton of exercises."
                        },
                        new
                        {
                            Id = 8,
                            Author = "Calculus by Michael Spivak",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 8000.0,
                            Title = "Spivak presents calculus as “the first real encounter with mathematics” and doesn’t just teach you the concepts of calculus."
                        },
                        new
                        {
                            Id = 9,
                            Author = "Calculus for Dummies by Mark Ryan",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 7000.0,
                            Title = "Do you have a hard time learning maths? This is the book to change that!"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Algebra: Structure and Method, Book 1\r\nby Richard G. Brown",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 15000.0,
                            Title = "The textbook breaks down basic algebraic theories and elementary practical principles at a middle grade and high school level."
                        },
                        new
                        {
                            Id = 11,
                            Author = "Algebra: A Complete Introduction: Teach Yourself\r\nby Hugh Neill",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 10000.0,
                            Title = "Neill’s textbook covers all the essential algebra topics from basic operations to quadratic equations and logarithms. This introduction is designed to help students improve their knowledge with clear explanations of algebra theory as well as examples and test questions"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Abstract Algebra\r\nby David Dummit and Richard Foote",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 2000.0,
                            Title = "Abstract Algebra advances key concepts that underpin algebraic structures. Dummit and Foote begin with the most basic theories and build on existing knowledge with numerous examples to help students best appreciate the mathematical theory and its"
                        },
                        new
                        {
                            Id = 13,
                            Author = " Mark J. Price",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 10000.0,
                            Title = " This comprehensive guide is perfect for beginners, exploring both C# 10 and .NET 6 in detail. Mark J. Price's approach ensures that readers not only learn the syntax but also understand the application of C# in creating modern, high-performing applications. The book includes numerous examples, exercises, and real-world scenarios."
                        },
                        new
                        {
                            Id = 14,
                            Author = "Jennifer Greene and Andrew Stellman",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 12000.0,
                            Title = "Dive into C# and create apps, user interfaces, games, and more using this fun and highly visual introduction to C#, .NET Core, and Visual Studio. With this completely updated guide, which covers C# 8.0 and Visual Studio 2019, beginning programmers like you will build a fully functional game in the opening chapter."
                        },
                        new
                        {
                            Id = 15,
                            Author = " Jon Skeet",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 1000.0,
                            Title = "C# in Depth is known for its thorough exploration of C#. Although it can be somewhat advanced, the book starts with fundamental concepts and gradually moves to more complex topics, making it a valuable resource for beginners aiming to deepen their knowledge. It's revered for its in-depth and meticulous examination of modern C#"
                        });
                });

            modelBuilder.Entity("Library_managment_system_API.Entities.BookCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Catagory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCatagory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Catagory = "Computer",
                            SubCatagory = "DataStructure"
                        },
                        new
                        {
                            Id = 2,
                            Catagory = "Mechanical",
                            SubCatagory = "Machine"
                        },
                        new
                        {
                            Id = 3,
                            Catagory = "Methamatics",
                            SubCatagory = "Calculas"
                        },
                        new
                        {
                            Id = 4,
                            Catagory = "Methamatics",
                            SubCatagory = "Algebra"
                        },
                        new
                        {
                            Id = 5,
                            Catagory = "Computer",
                            SubCatagory = "C# Programing"
                        });
                });

            modelBuilder.Entity("Library_managment_system_API.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("FinePaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Returned")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Library_managment_system_API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountStatus = "ACTIVE",
                            CreatedOn = new DateTime(2023, 12, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mehedi@gmail.com",
                            FirstName = "Mehedi",
                            LastName = "kazi",
                            MobileNumber = "01750323645",
                            Password = "Password1234",
                            UserType = "ADMIN"
                        });
                });

            modelBuilder.Entity("Library_managment_system_API.Entities.Book", b =>
                {
                    b.HasOne("Library_managment_system_API.Entities.BookCategory", "BbookCategory")
                        .WithMany()
                        .HasForeignKey("BookCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BbookCategory");
                });

            modelBuilder.Entity("Library_managment_system_API.Entities.Order", b =>
                {
                    b.HasOne("Library_managment_system_API.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library_managment_system_API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
